spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: C##CHOI_VUE
    password: oracle
  jpa:
    show-sql: true
    database: oracle
    hibernate:
      ddl-auto: update
  mvc:
    view:
      suffix: .html